apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 864981728406.dkr.ecr.ap-south-1.amazonaws.com/testing/my-flask-app:latest  # Replace with your Docker image
        ports:
        - containerPort: 5000  # Port your application listens on
